[package]
name = "aoc-autobench"
version = "0.2.1"
authors = ["Grégory Obanos <gregory.obanos@gmail.com>"]

[dependencies]
aoc2019 = { path = "../../.." }
aoc-runner = "0.2.2"

[dev-dependencies]
criterion = "0.2.5"



[[bench]]
name = "aoc_benchmark"
harness = false
